# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Allure CLI
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.32.2/allure-2.32.2.tgz
        tar -xvzf allure-2.32.2.tgz
        sudo ln -s $(pwd)/allure-2.32.2/bin/allure /usr/local/bin/allure
        allure --version
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Run Selenium tests
      run: mvn clean test || true

    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results

    - name: Serve Allure report (Optional)
      run: |
        allure generate allure-results -o allure-report

    - name: Deploy Allure report to gh-pages
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        # Create or switch to the gh-pages branch
        git checkout --orphan gh-pages
        # Move Allure report content to the root of gh-pages
        mv allure-report/* .
        git add .
        git commit -m "Update Allure report"
        # Push the report to the gh-pages branch
        git push origin gh-pages --force    
